name: stacked_card_carousel_example
description: Stacked card carousel example
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  stacked_card_carousel:
    path: ../
  shopper_package:
    git:
      url: https://gitlab.com/shopassist2/mobile/shoper_package
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
